server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  port: 8000

logging:
  level:
    com.itstudy.order.feign: debug

spring:
  profiles:
    active: test
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 47.111.179.30:8848
      config:
        namespace: ${spring.profiles.active:dev}
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    active:
      on-profile: dev

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    active:
      on-profile: test

