spring:
  application:
    name: seata-account
  datasource:
    url: jdbc:mysql://47.111.179.30:3305/account_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: account_db
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 47.111.179.30:8848
      config:
        import-check:
          enabled: false
server:
  port: 20000

mybatis:
  mapper-locations: classpath:mapper/*.xml
#seata:
#  data-source-proxy-mode: XA
