spring.application.name=service-product
server.port=9001

server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.cloud.nacos.server-addr=47.111.179.30:8848
spring.cloud.nacos.config.import-check.enabled=false